### ISSUE TITLE
package c14bazAAR has been removed from CRAN

### ISSUE THREAD

**Issue by corybrunson** [nevrome/bleiglas#12]
The README illustrates **bleiglas** functionality using the data set `c14` installed with the package **c14bazAAR**. However, the latter package has been removed from CRAN. (Check [the CRAN page](https://cran.r-project.org/package=c14bazAAR) to be sure.) Depending on that package's permissions, the data set could be installed with **bleiglas** instead; or, another data set could be used for illustration. But i believe it is inadvisable (anyway, i would advise against it!) to rely on a package that has been removed from CRAN, perhaps unless it is under active development with plans to restore it.

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/3092)._

**Comment by nevrome** [comment]
I'm the maintainer of c14bazAAR and it was removed from CRAN because of an issue in a dependency, not the package itself. c14bazAAR is still actively developed and part of the rOpenSci initiative, but I'm not planning to resubmit to CRAN at the moment.

I hope 8855d24 somehow mitigates your concern.

**Comment by corybrunson** [comment]
Yes, this is quite satisfactory! Thank you.
